"""Initial migration

Revision ID: 501764ad04d4
Revises: 
Create Date: 2025-04-04 14:21:42.980790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501764ad04d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('today_weather',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day', sa.String(length=50), nullable=True),
    sa.Column('sunrise', sa.String(length=50), nullable=True),
    sa.Column('sunset', sa.String(length=50), nullable=True),
    sa.Column('highest_temp', sa.String(length=10), nullable=True),
    sa.Column('lowest_temp', sa.String(length=10), nullable=True),
    sa.Column('wind_speed', sa.String(length=50), nullable=True),
    sa.Column('humidity', sa.String(length=10), nullable=True),
    sa.Column('dew_point', sa.String(length=10), nullable=True),
    sa.Column('pressure', sa.String(length=10), nullable=True),
    sa.Column('uv_index', sa.String(length=10), nullable=True),
    sa.Column('visibility', sa.String(length=10), nullable=True),
    sa.Column('moon_phase', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_forecast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day', sa.String(length=50), nullable=True),
    sa.Column('high_temp', sa.String(length=10), nullable=True),
    sa.Column('low_temp', sa.String(length=10), nullable=True),
    sa.Column('condition', sa.String(length=100), nullable=True),
    sa.Column('rain_percentage', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_forecast')
    op.drop_table('today_weather')
    # ### end Alembic commands ###
