"""Addition of day column on today_weather

Revision ID: f6c542c50e1b
Revises: 68f743af16bb
Create Date: 2025-04-03 13:51:59.489692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c542c50e1b'
down_revision = '68f743af16bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('today_weather', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('today_weather', schema=None) as batch_op:
        batch_op.drop_column('day')

    # ### end Alembic commands ###
